SELECT
	N.NOME_PESSOA
,	S.PASSWORD
FROM
	SENHA_MYSQL				S
,	PESSOA					P
,	PESSOA_IDENTIFICACAO	I
,	PESSOA_NOME				N
WHERE
	P.ID_PESSOA			=	S.ID_PESSOA
AND	P.ID_PESSOA			=	I.ID_PESSOA
AND	P.ID_PESSOA			=	N.ID_PESSOA
AND	P.SEQ_NOME			=	N.SEQ_NOME_PESSOA
AND	P.COD_TIPO_PESSOA	=	'PF'
AND	S.DTH_DESATIVACAO	IS	NULL
AND	S.SIN_ATIVO			=	'S'
AND	S.PASSWORD			=	'$2a$12$7cOkE3Y5bEQvd/N2eNZcWeTDdtTKM3k1p4lAYTiarLKOubG8MGEym'
AND	I.IDENT_PRINCIPAL	=	'vsv'